version: '2'
services:
  bareos-data:
    image: busybox
    volumes:
       - "${DATA_PATH}/bareos/etc:/etc/bareos/"
       - "${DATA_PATH}/log:/var/log/bareos/"
       - "${DATA_PATH}/sqlite:/var/lib/bareos/"
    container_name: "${COMPOSE_PROJECT_NAME}_bareos-data"

  bareos:
    environment:
       - "TZ=${TIMEZONE}"
    build:
      context: bareos
      dockerfile: Dockerfile
    hostname: ${COMPOSE_PROJECT_NAME}
    volumes_from:
      - bareos-data
    container_name: "${COMPOSE_PROJECT_NAME}_bareos"
    ports:
      -  "${HTTP_IP_PORT}:80"
    depends_on:
      - bareos-data
    restart: always
    logging:
      driver: none

