version: '2'
services:

  bareos:
    environment:
       - "TZ=${TIMEZONE}"
    build:
      context: bareos
      dockerfile: Dockerfile
    hostname: ${COMPOSE_PROJECT_NAME}
    container_name: "${COMPOSE_PROJECT_NAME}_bareos"
    ports:
      -  "${HTTP_IP_PORT}:80"
    restart: always
    volumes:
       - "${DATA_PATH}/bareos/etc/bareos:/etc/bareos/"
       - "${DATA_PATH}/bareos/etc/bareos-webui/etc:/etc/bareos-webui/"
       - "${DATA_PATH}/log:/var/log/bareos/"
       - "${DATA_PATH}/sqlite:/var/lib/bareos/"
    logging:
      driver: none

